#!/usr/bin/env python3

import fileinput


def read_file():
    with fileinput.input() as f_input:
        for line in f_input:
            print(line, end="")


if __name__ == '__main__':
    read_file()
